// HF-parity regression test.
//
// Loads each converted tokenizer asset, encodes the shared corpus with the C++
// engine, and checks the ids against golden ids captured from the upstream
// HuggingFace tokenizer (see tests/gen_golden.py). The engine may prepend
// prefix_tokens_, so the golden sequence is matched as a SUFFIX of the engine
// output (mirroring HF's add_special_tokens=False).
//
// No transformers / network needed at test time -- the golden files are committed.
//
//   usage: test_hf_parity [tests_dir]   (default tests_dir = "tests")
#include "tokenizer/tokenizer_optimized.hpp"
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using MNN::Transformer::Tokenizer;

static std::string unescape(const std::string& in) {
    std::string out;
    out.reserve(in.size());
    for (size_t i = 0; i < in.size(); ++i) {
        if (in[i] == '\\' && i + 1 < in.size()) {
            char n = in[i + 1];
            if (n == 'n') { out.push_back('\n'); ++i; continue; }
            if (n == 't') { out.push_back('\t'); ++i; continue; }
            if (n == 'r') { out.push_back('\r'); ++i; continue; }
            if (n == '\\') { out.push_back('\\'); ++i; continue; }
        }
        out.push_back(in[i]);
    }
    return out;
}

static std::vector<std::string> read_lines(const std::string& path, bool unescape_lines) {
    std::vector<std::string> v;
    std::ifstream f(path);
    std::string line;
    while (std::getline(f, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        v.push_back(unescape_lines ? unescape(line) : line);
    }
    return v;
}

static std::vector<std::vector<int>> read_golden(const std::string& path) {
    std::vector<std::vector<int>> v;
    std::ifstream f(path);
    std::string line;
    while (std::getline(f, line)) {
        std::istringstream ss(line);
        std::vector<int> ids;
        int id;
        while (ss >> id) ids.push_back(id);
        v.push_back(std::move(ids));
    }
    return v;
}

static bool ends_with(const std::vector<int>& a, const std::vector<int>& b) {
    if (a.size() < b.size()) return false;
    return std::equal(a.end() - (long)b.size(), a.end(), b.begin());
}

int main(int argc, char** argv) {
    const std::string base = (argc > 1) ? argv[1] : "tests";
    const auto corpus  = read_lines(base + "/golden/corpus.txt", /*unescape=*/true);
    const auto models  = read_lines(base + "/golden/manifest.txt", /*unescape=*/false);
    if (corpus.empty() || models.empty()) {
        fprintf(stderr, "could not read corpus/manifest under '%s' (run from repo root or pass tests dir)\n", base.c_str());
        return 2;
    }

    int total_mismatch = 0, total_checked = 0, models_failed = 0, models_skipped = 0;
    for (const auto& model : models) {
        if (model.empty()) continue;
        const std::string asset  = base + "/assets/" + model + ".txt";
        const std::string golden = base + "/golden/" + model + ".golden";
        // tests/assets is .gitignored (large, generated by convert_tokenizer.py), so a fresh
        // CI checkout won't have it. Treat a missing asset as a skip, not a failure: the test
        // runs fully for developers who have the assets, and stays green in CI without them.
        std::ifstream probe(asset);
        if (!probe.good()) { printf("[SKIP] %-26s (asset not present)\n", model.c_str()); ++models_skipped; continue; }
        probe.close();
        Tokenizer* tok = Tokenizer::createTokenizer(asset);
        if (!tok) { fprintf(stderr, "[%s] FAILED to load %s\n", model.c_str(), asset.c_str()); ++models_failed; continue; }
        const auto gold = read_golden(golden);

        int mism = 0;
        const size_t n = std::min(corpus.size(), gold.size());
        for (size_t i = 0; i < n; ++i) {
            std::vector<int> ids = tok->encode(corpus[i]);
            ++total_checked;
            if (!ends_with(ids, gold[i])) {
                if (mism < 3) {
                    fprintf(stderr, "  [%s] line %zu mismatch\n     exp(HF): ", model.c_str(), i);
                    for (int id : gold[i]) fprintf(stderr, "%d ", id);
                    fprintf(stderr, "\n     got    : ");
                    for (int id : ids) fprintf(stderr, "%d ", id);
                    fprintf(stderr, "\n");
                }
                ++mism;
            }
        }
        delete tok;
        printf("%s %-26s %zu/%zu lines match HF\n", mism == 0 ? "[ OK ]" : "[FAIL]", model.c_str(), n - mism, n);
        total_mismatch += mism;
        if (mism) ++models_failed;
    }

    printf("\n%d/%d encodings match HF (%d models checked, %d skipped, %d failed)\n",
           total_checked - total_mismatch, total_checked,
           (int)models.size() - models_skipped - models_failed, models_skipped, models_failed);
    if (total_checked == 0) {
        printf("note: no assets present -- run tests/convert_tokenizer.py to populate tests/assets/\n");
    }
    return (total_mismatch == 0 && models_failed == 0) ? 0 : 1;
}
